name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools podman binutils-aarch64-linux-gnu
          cargo install cross --locked

      - name: Build for x86_64 linux gnu
        run: |
          CROSS_CONTAINER_ENGINE=podman cross build --target x86_64-unknown-linux-gnu --release
          cp target/x86_64-unknown-linux-gnu/release/iwmenu iwmenu-x86_64-linux-gnu
          strip iwmenu-x86_64-linux-gnu

      - name: Build for aarch64 linux gnu
        run: |
          CROSS_CONTAINER_ENGINE=podman cross build --target aarch64-unknown-linux-gnu --release
          cp target/aarch64-unknown-linux-gnu/release/iwmenu iwmenu-aarch64-linux-gnu
          aarch64-linux-gnu-strip iwmenu-aarch64-linux-gnu

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: iwmenu-*
          generate_release_notes: true
          prerelease: ${{ contains(github.ref, '-') }}
